### ISSUE TITLE
Task cancellation question

### ISSUE THREAD

**Issue by Smaug123** [bhlieberman/fsbaseball#1]
Saw your question on r/fsharp. A few issues with the code:

--- 

https://github.com/bhlieberman/fsbaseball/blob/72143d52bebb962aff53224084825e726e27235b/Lookup.fs#L80

This is almost certainly not what you wanted. `task` is "hot-started": the act of creating a `task` is the act of starting it, on the current thread, running until the first yield point. The task you have created here will *finish* before you even call `_.Start` on it, because it has no yield points (and also calling `_.Start >> ignore` will do nothing anyway - try explicitly type-annotating the `ignore<_>` function to see why! `.Start` does not do what you think it does). Instead, consider using `backgroundTask` and not calling `_.Start` on it, or consider using `async` (which runs nothing until explicitly started somehow) so that you have explicit control over when it runs. 

---

https://github.com/bhlieberman/fsbaseball/blob/72143d52bebb962aff53224084825e726e27235b/Lookup.fs#L67

Note that this will eagerly start the `createRegister` task (which immediately yields, so this isn't the same problem as the previous one; the main executing thread will indeed proceed). The way the code is phrased, though, I suspect you didn't intend it to start at this point; I suspect you intended it to start when you call `runCreate` or similar. As it stands, the `Console.WriteLine`s could in principle execute only *after* all the work is complete!

I recommend using `async` instead, which is much simpler to reason about. `task` I consider to be somewhat advanced until you have your mental model of .NET asynchrony straightened out.

---

If all you're doing is waiting for a timeout, consider not creating a cancellation token and instead just use `.Wait (TimeSpan.FromSeconds blah)`. Fewer moving parts that way.

**Comment by bhlieberman** [comment]
Thanks a lot for your detailed comments. This is illuminating. As for the first issue, I went this route:
```fsharp
async {
                File.WriteAllLines(registerPath, [| "Name_first,Name_last,Key_mlbam" |])
                new MlbLookup(lookupTable) |> _.Save(registerPath)
            } |> Async.RunSynchronously
```
This solves the issue with cancellation, at least on a spot-check basis. Initially, I did try to remove this code from any nested computation entirely, and was perplexed that it threw an `IOException`. I suppose this is because tasks don't provide any guarantees about execution order, and that some other part of the code (or else another computation) was touching this file at the same time. In any case, using `async` here was a quick fix. I don't totally follow you on the concept of yield points, yet, but I'll have to look more into those. Thanks again for your help, it's very much appreciated!

**Comment by Smaug123** [comment]
Note also that `async { blah } |> Async.RunSynchronously` is essentially the same as `blah`: it will construct a workload, and then run it on the current thread synchronously, meaning no concurrency. If you want to write to a file in the background, you might want `Async.StartAsTask` to put the work into the thread pool instead (it will return a running `Task`).

(By "yield point" I mean a usage of `let!` or `do!` or `use!`: in C# this is effectively the same as `await`, but in F# the machinery is that of the much more general "computation expressions", of which `async`, `task`, and `seq` are three examples.)

**Comment by bhlieberman** [comment]
Oh, that all makes sense. I was using those yield points without knowing them by name. I actually have no .NET experience, but I've written a little bit of Haskell here and there and can see how computation expressions behave like very general monads. They are quite interesting.
